[build]
  publish = "."
  command = ""

[build.environment]
  HUGO_VERSION = ""

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
